//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails
    {
        public int InvoiceDetailID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string ProductName { get; set; }
        public string AmountUnit { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<float> UnitPrice { get; set; }
    
        public virtual Invoices Invoices { get; set; }
    }
}
